# Generated by Django 2.0 on 2020-03-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0003_auto_20200315_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='subjects',
            new_name='student_class',
        ),
    ]
